import { Canvas } from "@react-three/fiber"
import type { NextPage } from "next"
import Head from "next/head"
import Header from "../components/Header"
import Bodymap_footLEFT from "../Bodymap_footLEFT"
import { Suspense } from "react"
import Model from "../Bodymap_footLEFT"
import { OrbitControls } from "@react-three/drei"
import Footer from "../components/Footer"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen">
        <Header />
        <Canvas style={{ width: "100vw", height: "80vh" }}>
          <Suspense fallback={null}>
            <OrbitControls />
            <Model />
          </Suspense>
        </Canvas>
        <Footer />
      </main>
    </>
  )
}

export default Home
